# Site settings
title: "Alain Deléglise"
description: "Mon Curiculum Vitae"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "false"
resume_name:                    "Alain Deléglise"
resume_title:                   "Ingénieur Avant-vente / Architecte Infrastructure"
resume_contact_email:           "alain.deleglise@alterway.fr"
resume_contact_telephone:       "01 41 16 83 42"
resume_contact_address:         "166 bis Avenue de Bretagne - 59000 Lille"
resume_header_contact_info: "166 bis Avenue de Bretagne - 59000 Lille | 01 41 16 83 42 | alain.deleglise@alterway.fr"
resume_header_intro: "<p>Je suis toujours à la recherche de nouveaux challenges. J'aime relever des défis, techniques ou fontionnels, qui m'aident à développer mes compétences. J'ai une appétance particulière pour le monde du logiciel libre et je tente, autant que faire ce peux, d'apporter ma contribution aux communautés.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "no"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/adeleglise/resume-template"
  resume_twitter_url:           "http://twitter.com/alaindeleglise"
  resume_dribbble_url:          "https://dribbble.com/"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/alaindeleglise"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://alain.deleglise.net"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
